import type { Metadata } from "next";
import "./globals.css";
import ResponsiveNavbar from "@/shared/layout/responsive-navbar";
import Footer from "@/shared/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ResponsiveNavbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
